"""add account_status_id, surname, given_name to  users table

Revision ID: 7cb3bb78ea41
Revises: 03cd32c50eb8
Create Date: 2022-07-07 10:29:33.508627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb3bb78ea41'
down_revision = '03cd32c50eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.String(), server_default='', nullable=False))
    op.add_column('users', sa.Column('given_name', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'given_name')
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###
