"""create users_in_formosa_table, users_in_formosa_details and users_in_formosa_status table

Revision ID: d56c431cfa3f
Revises: 03cd32c50eb8
Create Date: 2022-07-08 12:25:58.697035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from persistences.postgresql.modules.user.users_status import users_status_table

# revision identifiers, used by Alembic.
revision = "d56c431cfa3f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "users_detail_in_formosa",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("surname", sa.VARCHAR(length=30), server_default="", nullable=False),
        sa.Column(
            "given_name", sa.VARCHAR(length=50), server_default="", nullable=False
        ),
        sa.Column(
            "gender",
            postgresql.ENUM(
                "Not_known",
                "Male",
                "Female",
                "Not_aplicable",
                name="gender",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("formosa_id_card_letter", sa.VARCHAR(length=1), nullable=False),
        sa.Column("formosa_id_card", sa.VARCHAR(length=9), nullable=False),
        sa.Column("address1", sa.VARCHAR(length=255), nullable=False),
        sa.Column("address2", sa.VARCHAR(length=255), nullable=False),
        sa.Column("address3", sa.VARCHAR(length=255), nullable=False),
        sa.Column("country", sa.VARCHAR(length=255), nullable=False),
        sa.Column("city", sa.VARCHAR(length=255), nullable=False),
        sa.Column("region", sa.VARCHAR(length=255), nullable=False),
        sa.Column("zip_code", sa.VARCHAR(length=6), nullable=False),
        sa.Column("country_code", sa.VARCHAR(length=4), nullable=False),
        sa.Column("subscriber_number", sa.VARCHAR(length=9), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=False),
        sa.Column(
            "last_update",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users_status",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "activate", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "forbidden", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.bulk_insert(
        users_status_table,
        [
            {
                "id": 0,
                "activate": False,
                "forbidden": False,
            },
            {
                "id": 1,
                "activate": True,
                "forbidden": False,
            },
            {
                "id": 2,
                "activate": False,
                "forbidden": True,
            },
        ],
    )
    op.create_table(
        "users_in_formosa",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_detail_in_formosa_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "user_status_id", sa.BigInteger(), server_default="0", nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=50), nullable=False),
        sa.Column("password", sa.VARCHAR(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "forbidden_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("NULL"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_status_id"],
            ["users_status.id"],
            name="FK__users_in_formosa__users_status_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_detail_in_formosa_id"],
            ["users_detail_in_formosa.id"],
            name="FK_users_in_formosa__users_details_in_formosa_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "FK__users_in_formosa__users_status_id",
        "users_in_formosa",
        type_="foreignkey",
    )
    op.drop_table("users_status")
    op.drop_constraint(
        "FK_users_in_formosa__users_details_in_formosa_id",
        "users_in_formosa",
        type_="foreignkey",
    )
    op.drop_table("users_detail_in_formosa")
    op.drop_table("users_in_formosa")
    # ### end Alembic commands ###
