"""add vote schema

Revision ID: 03cd32c50eb8
Revises: 2c6d65b42c8a
Create Date: 2022-06-07 15:03:05.716982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03cd32c50eb8"
down_revision = "2c6d65b42c8a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "votes",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users_in_formosa.id"],
            name="FK__votes__users_in_formosa_id",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["posts.id"],
            name="FK__votes__posts_id",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "post_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("FK__votes__users_in_formosa_id", "votes", type_="foreignkey")
    op.drop_constraint("FK__votes__posts_id", "votes", type_="foreignkey")
    op.drop_table("votes")
    # ### end Alembic commands ###
